apiVersion: v1
kind: Pod
metadata:
 name: kaniko
spec:
 containers:
 - name: kaniko
   image: gcr.io/kaniko-project/executor:latest
   args: ["--dockerfile=Dockerfile",
           "--context=.",
           "--destination=anaisurlichs/demo:1.0.0"] # replace with your dockerhub account
   volumeMounts:
     - name: dockerfile-storage
       mountPath: /workspace
 restartPolicy: Never
 volumes:
   - name: dockerfile-storage
     persistentVolumeClaim:
       claimName: dockerfile-claim
